# Generated by Django 5.1.4 on 2025-05-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='order_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
